package gobd2

// CommandCode represents OBD-II command code.
type CommandCode string

// Constants for ELM327-compatible OBD-II command codes.
const (
	// Show PIDs supported.
	SupportedPIDsCommand1_20  CommandCode = "0100"
	SupportedPIDsCommand21_40 CommandCode = "0120"
	SupportedPIDsCommand41_60 CommandCode = "0140"
	SupportedPIDsCommand61_80 CommandCode = "0160"

	// Engine and Emission Measurements.
	MonitorStatusCommand               CommandCode = "0101"
	FreezeDTCCommand                   CommandCode = "0102"
	FuelSystemStatusCommand            CommandCode = "0103"
	EngineLoadCommand                  CommandCode = "0104"
	CoolantTemperatureCommand          CommandCode = "0105"
	ShortTermFuelTrimBank1Command      CommandCode = "0106"
	LongTermFuelTrimBank1Command       CommandCode = "0107"
	ShortTermFuelTrimBank2Command      CommandCode = "0108"
	LongTermFuelTrimBank2Command       CommandCode = "0109"
	FuelPressureCommand                CommandCode = "010A"
	IntakeManifoldPressureCommand      CommandCode = "010B"
	EngineRPMCommand                   CommandCode = "010C"
	VehicleSpeedCommand                CommandCode = "010D"
	TimingAdvanceCommand               CommandCode = "010E"
	IntakeAirTemperatureCommand        CommandCode = "010F"
	MAFCommand                         CommandCode = "0110"
	ThrottlePositionCommand            CommandCode = "0111"
	CommandedSecondaryAirStatusCommand CommandCode = "0112"
	OxygenSensorsPresentCommand        CommandCode = "0113"
	OxygenSensor1Command               CommandCode = "0114"
	OxygenSensor2Command               CommandCode = "0115"
	OxygenSensor3Command               CommandCode = "0116"
	OxygenSensor4Command               CommandCode = "0117"
	OxygenSensor5Command               CommandCode = "0118"
	OxygenSensor6Command               CommandCode = "0119"
	OxygenSensor7Command               CommandCode = "011A"
	OxygenSensor8Command               CommandCode = "011B"
	OBDStandardsCommand                CommandCode = "011C"
	OxygenSensorsPresent2Command       CommandCode = "011D"
	AuxiliaryInputStatusCommand        CommandCode = "011E"
	RunTimeSinceEngineStartCommand     CommandCode = "011F"

	// Additional PIDs for Distance and System Monitoring.
	DistanceTraveledWithMILCommand           CommandCode = "0121"
	FuelRailPressureVacuumCommand            CommandCode = "0122"
	FuelRailPressureDirectCommand            CommandCode = "0123"
	O2Sensor1FuelAirEquivalenceCommand       CommandCode = "0124"
	O2Sensor2FuelAirEquivalenceCommand       CommandCode = "0125"
	O2Sensor3FuelAirEquivalenceCommand       CommandCode = "0126"
	O2Sensor4FuelAirEquivalenceCommand       CommandCode = "0127"
	O2Sensor5FuelAirEquivalenceCommand       CommandCode = "0128"
	O2Sensor6FuelAirEquivalenceCommand       CommandCode = "0129"
	O2Sensor7FuelAirEquivalenceCommand       CommandCode = "012A"
	O2Sensor8FuelAirEquivalenceCommand       CommandCode = "012B"
	CommandedEGRCommand                      CommandCode = "012C"
	EGRErrorCommand                          CommandCode = "012D"
	CommandedEvaporativePurgeCommand         CommandCode = "012E"
	FuelTankLevelInputCommand                CommandCode = "012F"
	WarmupsSinceCodesClearedCommand          CommandCode = "0130"
	DistanceTraveledSinceCodesClearedCommand CommandCode = "0131"
	EvapSystemVaporPressureCommand           CommandCode = "0132"
	BarometricPressureCommand                CommandCode = "0133"
	CatalystTemperatureBank1Sensor1Command   CommandCode = "013C"
	CatalystTemperatureBank2Sensor1Command   CommandCode = "013D"
	CatalystTemperatureBank1Sensor2Command   CommandCode = "013E"
	CatalystTemperatureBank2Sensor2Command   CommandCode = "013F"

	// Diagnostic commands.
	DiagnosticTroubleCodesClearedCommand    CommandCode = "014A"
	ControlModuleVoltageCommand             CommandCode = "0142"
	AbsoluteLoadValueCommand                CommandCode = "0143"
	FuelAirCommandedEquivalenceRatioCommand CommandCode = "0144"
	RelativeThrottlePositionCommand         CommandCode = "0145"
	AmbientAirTemperatureCommand            CommandCode = "0146"
	ThrottlePositionBCommand                CommandCode = "0147"
	ThrottlePositionCCommand                CommandCode = "0148"
	AcceleratorPedalPositionDCommand        CommandCode = "0149"
	AcceleratorPedalPositionECommand        CommandCode = "014A"
	AcceleratorPedalPositionFCommand        CommandCode = "014B"
	CommandedThrottleActuatorCommand        CommandCode = "014C"
	TimeRunWithMILCommand                   CommandCode = "014D"
	TimeSinceTroubleCodesClearedCommand     CommandCode = "014E"
)
